name: Chimera CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache-pypoetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: python-poetry
        run: pip install poetry==1.8.5 setuptools && poetry run python -m pip install -U pip

      - name: install-deps
        run: poetry lock --no-update && poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - uses: actions/checkout@v4

      - name: cache-pypoetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: pre-commit
        run: poetry run pre-commit run -a -v
