name: Chimera CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: poetry
        run: pip install poetry==1.8.5 setuptools && poetry run python -m pip install -U pip

      - name: install-deps
        run: poetry lock --no-update && poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"
          cache: "poetry"

      - name: pre-commit
        run: poetry run pre-commit run -a -v
